import { describe, it, expect } from "vitest";
import { CodepointMeta } from "../types";

// Helper to fabricate a minimal CodepointMeta with only fields used by processDescriptions
function metaWith(
  rawDescription: string,
  wiki: { abstract: string; lang: string; src: string } | null
): CodepointMeta {
  return {
    cp: 0,
    age: "",
    na: "",
    na1: "",
    gc: "",
    ccc: "" as any,
    bc: "",
    Bidi_M: false,
    Bidi_C: false,
    dt: "",
    CE: false,
    Comp_Ex: false,
    NFC_QC: "",
    NFD_QC: "",
    NFKC_QC: "",
    NFKD_QC: "",
    XO_NFC: false,
    XO_NFD: false,
    XO_NFKC: false,
    XO_NFKD: false,
    nt: "",
    jt: "",
    jg: "",
    Join_C: false,
    lb: "",
    ea: "",
    Upper: false,
    Lower: false,
    OUpper: false,
    OLower: false,
    CI: false,
    Cased: false,
    CWCF: false,
    CWCM: false,
    CWL: false,
    CWKCF: false,
    CWT: false,
    CWU: false,
    isc: "",
    hst: "",
    JSN: "",
    InSC: "",
    InMC: null,
    InPC: "",
    IDS: false,
    OIDS: false,
    XIDS: false,
    IDC: false,
    OIDC: false,
    XIDC: false,
    Pat_Syn: false,
    Pat_WS: false,
    Dash: false,
    Hyphen: false,
    QMark: false,
    Term: false,
    STerm: false,
    Dia: false,
    Ext: false,
    SD: false,
    Alpha: false,
    OAlpha: false,
    Math: false,
    OMath: false,
    Hex: false,
    AHex: false,
    DI: false,
    ODI: false,
    LOE: false,
    WSpace: false,
    Gr_Base: false,
    Gr_Ext: false,
    OGr_Ext: false,
    Gr_Link: false,
    GCB: "",
    WB: "",
    SB: "",
    Ideo: false,
    UIdeo: false,
    IDSB: false,
    IDST: false,
    Radical: false,
    Dep: false,
    VS: false,
    NChar: false,
    kAccountingNumeric: null,
    kAlternateHanYu: null,
    kAlternateJEF: null,
    kAlternateKangXi: null,
    kAlternateMorohashi: null,
    kBigFive: null,
    kCCCII: null,
    kCNS1986: null,
    kCNS1992: null,
    kCangjie: null,
    kCantonese: null,
    kCheungBauer: null,
    kCheungBauerIndex: null,
    kCihaiT: null,
    kCompatibilityVariant: null,
    kCowles: null,
    kDaeJaweon: null,
    kDefinition: null,
    kEACC: null,
    kFenn: null,
    kFennIndex: null,
    kFourCornerCode: null,
    kFrequency: null,
    kGB0: null,
    kGB1: null,
    kGB3: null,
    kGB5: null,
    kGB7: null,
    kGB8: null,
    kGradeLevel: null,
    kGSR: null,
    kHangul: null,
    kHanYu: null,
    kHanyuPinlu: null,
    kHanyuPinyin: null,
    kHDZRadBreak: null,
    kHKGlyph: null,
    kHKSCS: null,
    kIBMJapan: null,
    kIICore: null,
    kIRGDaeJaweon: null,
    kIRGDaiKanwaZiten: null,
    kIRGHanyuDaZidian: null,
    kIRGKangXi: null,
    kIRG_GSource: null,
    kIRG_HSource: null,
    kIRG_JSource: null,
    kIRG_KPSource: null,
    kIRG_KSource: null,
    kIRG_MSource: null,
    kIRG_TSource: null,
    kIRG_USource: null,
    kIRG_VSource: null,
    kJHJ: null,
    kJIS0213: null,
    kJa: null,
    kJapaneseKun: null,
    kJapaneseOn: null,
    kJis0: null,
    kJis1: null,
    kKPS0: null,
    kKPS1: null,
    kKSC0: null,
    kKSC1: null,
    kKangXi: null,
    kKarlgren: null,
    kKorean: null,
    kLau: null,
    kMainlandTelegraph: null,
    kMandarin: null,
    kMatthews: null,
    kMeyerWempe: null,
    kMorohashi: null,
    kNelson: null,
    kOtherNumeric: null,
    kPhonetic: null,
    kPrimaryNumeric: null,
    kPseudoGB1: null,
    kRSAdobe_Japan1_6: null,
    kRSJapanese: null,
    kRSKanWa: null,
    kRSKangXi: null,
    kRSKorean: null,
    kRSMerged: null,
    kRSUnicode: null,
    kSBGY: null,
    kSemanticVariant: null,
    kSimplifiedVariant: null,
    kSpecializedSemanticVariant: null,
    kTaiwanTelegraph: null,
    kTang: null,
    kTotalStrokes: null,
    kTraditionalVariant: null,
    kVietnamese: null,
    kXHC1983: null,
    kWubi: null,
    kXerox: null,
    kZVariant: null,
    blk: "",
    scx: null,
    bpt: "",
    image: null,
    sc: "",
    abstract: null,
    cf: [],
    NFKC_CF: [],
    lc: [],
    FC_NFKC: [],
    slc: [],
    bpb: [],
    uc: [],
    tc: [],
    suc: [],
    stc: [],
    scf: [],
    dm: [],
    _: {
      description: rawDescription,
      image: "",
      imagesource: "",
      wikipedia: wiki,
    },
  } as unknown as CodepointMeta;
}

// Frozen snippets (trimmed) from 2025-09-08 for the given codepoints
const desc316F = `<!-- codepoint -->\n<p>U+316F was added in Unicode version <a rel="nofollow" href="/search?age=1.1">1.1</a> in 1993. It belongs to the block <a class="ln bl" rel="up" href="/hangul_compatibility_jamo"><span class="meta">U+3130 to U+318F</span> <svg width="16" height="16"><svg viewBox="194 97 1960 1960" width="100%" height="100%"><use xlink:href="/static/assets/LastResort-CqQNoI4I.svg#compatibilityjamo"/></svg></svg> <span class="title">Hangul Compatibility Jamo</span></a>. </p>\n\n<!-- character -->\n<p>This character is a <strong>Other Letter</strong> and is mainly used in the <strong>Hangul</strong> script.</p>\n\n<!-- glyph -->\n<p>The glyph is a <strong>compatibility</strong> version of the glyph <a class="ln cp" href="/U+11DD"><svg width="16" height="16"><title>Glyph for U+11DD</title><use href="/image/1100.svg#U11DD"/></svg> <span class="title">Hangul Jongseong Mieum-Sios</span></a>.</p>`;

const desc65BB = `<!-- codepoint -->\n<p>U+65BB was added in Unicode version <a rel="nofollow" href="/search?age=1.1">1.1</a> in 1993. It belongs to the block <a class="ln bl" rel="up" href="/cjk_unified_ideographs"><span class="meta">U+4E00 to U+9FFF</span> <svg width="16" height="16"><svg viewBox="194 97 1960 1960" width="100%" height="100%"><use xlink:href="/static/assets/LastResort-CqQNoI4I.svg#cjkideograph"/></svg></svg> <span class="title">CJK Unified Ideographs</span></a>. </p>\n\n<!-- character -->\n<p>This character is a <strong>Other Letter</strong> and is mainly used in the <strong>Han</strong> script.</p>\n\n<!-- glyph -->\n<p>The glyph is <strong>not a composition</strong>. Its East Asian Width is <strong>wide</strong>.</p>`;

const cp316F = metaWith(desc316F, {
  abstract: `<p>\n</p>\n\n\n\n<p>The <b>Korean alphabet</b>, known as <b>Hangul</b> or <b>Hangeul</b> in South Korea (<span><span>English: </span></span> <i title="English pronunciation respelling"><span>HAHN</span>-gool</i>; Korean: <span title="Korean-language text"><span lang="ko-Hang">한글</span></span>; <span>Korean pronunciation:</span> <span lang="ko-Latn-fonipa">[ha(ː)n.ɡɯɭ]</span>) and <b>Chosŏn'gŭl</b> in North Korea (<span title="Korean-language text"><span lang="ko-Hang">조선글</span></span>; <span>North Korean pronunciation</span> <span lang="ko-Latn-fonipa">[tsʰo.sʰɔn.ɡɯɭ]</span>), is the modern writing system for the Korean language. The letters for the five basic consonants reflect the shape of the speech organs used to pronounce them. They are systematically modified to indicate phonetic features. The vowel letters are systematically modified for related sounds, making Hangul a featural writing system. It has been described as a syllabic alphabet as it combines the features of alphabetic and syllabic writing systems.\n</p><p>Hangul was created in 1443 CE by Sejong the Great, fourth king of the Joseon dynasty. It was an attempt to increase literacy by serving as a complement (or alternative) to the logographic Sino-Korean <i>Hanja</i>, which had been used by Koreans as their primary script to write the Korean language since as early as the Gojoseon period (spanning more than a thousand years and ending around 108 BCE), along with the usage of Classical Chinese.\n</p><p>Modern Hangul orthography uses 24 basic letters: 14 consonant letters and 10 vowel letters.  There are also 27 complex letters that are formed by combining the basic letters: 5 tense consonant letters, 11 complex consonant letters, and 11 complex vowel letters. Four basic letters in the original alphabet are no longer used: 1 vowel letter and 3 consonant letters. Korean letters are written in syllabic blocks with the alphabetic letters arranged in two dimensions. For example, the South Korean city of Seoul is written as <span title="Korean-language text"><span lang="ko">서울</span></span>, not <span title="Korean-language text"><span lang="ko">ㅅㅓㅇㅜㄹ</span></span>. The syllables begin with a consonant letter, then a vowel letter, and then potentially another consonant letter called a <i>batchim</i> (Korean: <span title="Korean-language text"><span lang="ko-Hang">받침</span></span>). If the syllable begins with a vowel sound, the consonant ㅇ (ng) acts as a silent placeholder. However, when ㅇ starts a sentence or is placed after a long pause, it marks a glottal stop. Syllables may begin with basic or tense consonants but not complex ones. The vowel can be basic or complex, and the second consonant can be basic, complex or a limited number of tense consonants. How the syllable is structured depends if the baseline of the vowel symbol is horizontal or vertical. If the baseline is vertical, the first consonant and vowel are written above the second consonant (if present), but all components are written individually from top to bottom in the case of a horizontal baseline.\n</p><p>As in traditional Chinese and Japanese writing, as well as many other texts in East Asia, Korean texts were traditionally written top to bottom, right to left, as is occasionally still the way for stylistic purposes. However, Korean is now typically written from left to right with spaces between words serving as dividers, unlike in Japanese and Chinese. Hangul is the official writing system throughout Korea, both North and South. It is a co-official writing system in the Yanbian Korean Autonomous Prefecture and Changbai Korean Autonomous County in Jilin Province, China. Hangul has also seen limited use by speakers of the Cia-Cia language in Indonesia.\n</p>`,
  lang: "en",
  src: "https://en.wikipedia.org/wiki/%E3%85%AF",
});
const cp65BB = metaWith(desc65BB, null);

import { processDescriptions } from "../utils";

const titles = (ds: { title: string }[]) => ds.map((d) => d.title);

describe("processDescriptions", () => {
  it("parses sections and sanitizes (316F with wiki)", () => {
    const d316F = processDescriptions(cp316F);
    expect(d316F).toStrictEqual([
      {
        title: "Codepoint",
        html: "<p>U+316F was added in Unicode version <u>1.1</u> in 1993. It belongs to the block <u><span>U+3130 to U+318F</span>  <span>Hangul Compatibility Jamo</span></u>. </p>",
      },
      {
        title: "Character",
        html: "<p>This character is a <strong>Other Letter</strong> and is mainly used in the <strong>Hangul</strong> script.</p>",
      },
      {
        title: "Glyph",
        html: "<p>The glyph is a <strong>compatibility</strong> version of the glyph <u> <span>Hangul Jongseong Mieum-Sios</span></u>.</p>",
      },
      {
        title: "Wikipedia (en)",
        html:
          `<p>The <b>Korean alphabet</b>, known as <b>Hangul</b> or <b>Hangeul</b> in South Korea (<span><span>English: </span></span> <i title="English pronunciation respelling"><span>HAHN</span>-gool</i>; Korean: <span title="Korean-language text"><span lang="ko-Hang">한글</span></span>; <span>Korean pronunciation:</span> <span lang="ko-Latn-fonipa">[ha(ː)n.ɡɯɭ]</span>) and <b>Chosŏn'gŭl</b> in North Korea (<span title="Korean-language text"><span lang="ko-Hang">조선글</span></span>; <span>North Korean pronunciation</span> <span lang="ko-Latn-fonipa">[tsʰo.sʰɔn.ɡɯɭ]</span>), is the modern writing system for the Korean language. The letters for the five basic consonants reflect the shape of the speech organs used to pronounce them. They are systematically modified to indicate phonetic features. The vowel letters are systematically modified for related sounds, making Hangul a featural writing system. It has been described as a syllabic alphabet as it combines the features of alphabetic and syllabic writing systems.\n` +
          "</p><p>Hangul was created in 1443 CE by Sejong the Great, fourth king of the Joseon dynasty. It was an attempt to increase literacy by serving as a complement (or alternative) to the logographic Sino-Korean <i>Hanja</i>, which had been used by Koreans as their primary script to write the Korean language since as early as the Gojoseon period (spanning more than a thousand years and ending around 108 BCE), along with the usage of Classical Chinese.\n" +
          '</p><p>Modern Hangul orthography uses 24 basic letters: 14 consonant letters and 10 vowel letters.  There are also 27 complex letters that are formed by combining the basic letters: 5 tense consonant letters, 11 complex consonant letters, and 11 complex vowel letters. Four basic letters in the original alphabet are no longer used: 1 vowel letter and 3 consonant letters. Korean letters are written in syllabic blocks with the alphabetic letters arranged in two dimensions. For example, the South Korean city of Seoul is written as <span title="Korean-language text"><span lang="ko">서울</span></span>, not <span title="Korean-language text"><span lang="ko">ㅅㅓㅇㅜㄹ</span></span>. The syllables begin with a consonant letter, then a vowel letter, and then potentially another consonant letter called a <i>batchim</i> (Korean: <span title="Korean-language text"><span lang="ko-Hang">받침</span></span>). If the syllable begins with a vowel sound, the consonant ㅇ (ng) acts as a silent placeholder. However, when ㅇ starts a sentence or is placed after a long pause, it marks a glottal stop. Syllables may begin with basic or tense consonants but not complex ones. The vowel can be basic or complex, and the second consonant can be basic, complex or a limited number of tense consonants. How the syllable is structured depends if the baseline of the vowel symbol is horizontal or vertical. If the baseline is vertical, the first consonant and vowel are written above the second consonant (if present), but all components are written individually from top to bottom in the case of a horizontal baseline.\n' +
          "</p><p>As in traditional Chinese and Japanese writing, as well as many other texts in East Asia, Korean texts were traditionally written top to bottom, right to left, as is occasionally still the way for stylistic purposes. However, Korean is now typically written from left to right with spaces between words serving as dividers, unlike in Japanese and Chinese. Hangul is the official writing system throughout Korea, both North and South. It is a co-official writing system in the Yanbian Korean Autonomous Prefecture and Changbai Korean Autonomous County in Jilin Province, China. Hangul has also seen limited use by speakers of the Cia-Cia language in Indonesia.\n" +
          "</p>",
      },
    ]);
  });

  it("parses sections without wikipedia (65BB)", () => {
    const d65BB = processDescriptions(cp65BB);
    expect(d65BB).toStrictEqual([
      {
        title: "Codepoint",
        html: "<p>U+65BB was added in Unicode version <u>1.1</u> in 1993. It belongs to the block <u><span>U+4E00 to U+9FFF</span>  <span>CJK Unified Ideographs</span></u>. </p>",
      },
      {
        title: "Character",
        html: "<p>This character is a <strong>Other Letter</strong> and is mainly used in the <strong>Han</strong> script.</p>",
      },
      {
        title: "Glyph",
        html: "<p>The glyph is <strong>not a composition</strong>. Its East Asian Width is <strong>wide</strong>.</p>",
      },
    ]);
  });
});
