/* eslint-disable */
// Generated by Wrangler by running `wrangler types src\env.d.ts --env-interface WorkerBindings --include-runtime false --strict-vars false --env-file .env.example` (hash: b13f0065b479abfb5f3b9f5023f04d1b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		TRMNL_WORKERS_KV: KVNamespace;
		TRMNL_DATA_SOURCE: string;
		TRMNL_SCHEDULE_TARGET: string;
		SCHEDULE_PAD_MINUTES: string;
		SCHEDULE_UPDATER_DRY_RUN: string;
		OIDC_PROXY_ALLOWED_ORIGINS: string;
		OIDC_PROXY_ALLOW_LOCALHOST: string;
		OIDC_PROXY_ALLOWED_CLIENT_IDS: string;
		TRMNL_API_KEY: string;
		GITHUB_TOKEN: string;
		OPENROUTER_API_KEY: string;
	}
}
interface WorkerBindings extends Cloudflare.Env {}
