/* eslint-disable */
// Generated by Wrangler by running `wrangler types src\env.d.ts --env-interface WorkerBindings --include-runtime false --strict-vars false --env-file .env.example` (hash: 6551f84b4770be3a50b5ab5b5b731c53)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		TRMNL_WORKERS_KV: KVNamespace;
		TRMNL_API_KEY: string;
		TRMNL_DATA_SOURCE: string;
		TRMNL_SCHEDULE_TARGET: string;
		SCHEDULE_PAD_MINUTES: string;
		SCHEDULE_UPDATER_DRY_RUN: string;
		GITHUB_TOKEN: string;
		OPENROUTER_API_KEY: string;
	}
}
interface WorkerBindings extends Cloudflare.Env {}
