export const Languages = [
  {"lang":"eng","bcp47":"en","name":"English","label":"En"},
  {"lang":"rus","bcp47":"ru","name":"Russian","label":"Ру"},
  {"lang":"ita","bcp47":"it","name":"Italian","label":"It"},
  {"lang":"epo","bcp47":"eo","name":"Esperanto","label":"Eo"},
  {"lang":"kab","bcp47":"kab","name":"Kabyle","label":"Kb"},
  {"lang":"tur","bcp47":"tr","name":"Turkish","label":"Tü"},
  {"lang":"deu","bcp47":"de","name":"German","label":"De"},
  {"lang":"fra","bcp47":"fr","name":"French","label":"Fr"},
  {"lang":"ber","bcp47":"ber","name":"Berber","label":"Br"},
  {"lang":"por","bcp47":"pt","name":"Portuguese","label":"Pt"},
  {"lang":"spa","bcp47":"es","name":"Spanish","label":"Es"},
  {"lang":"hun","bcp47":"hu","name":"Hungarian","label":"Hu"},
  {"lang":"jpn","bcp47":"ja","name":"Japanese","label":"日"},
  {"lang":"heb","bcp47":"he","name":"Hebrew","label":"עב"},
  {"lang":"nld","bcp47":"nl","name":"Dutch","label":"Nl"},
  {"lang":"ukr","bcp47":"uk","name":"Ukrainian","label":"Ук"},
  {"lang":"fin","bcp47":"fi","name":"Finnish","label":"Fi"},
  {"lang":"lit","bcp47":"lt","name":"Lithuanian","label":"Lt"},
  {"lang":"pol","bcp47":"pl","name":"Polish","label":"Pl"},
  {"lang":"ces","bcp47":"cs","name":"Czech","label":"Cs"},
  {"lang":"cmn","bcp47":"zh","name":"Mandarin Chinese","label":"普"},
  {"lang":"mar","bcp47":"mr","name":"Marathi","label":"मा"},
  {"lang":"mkd","bcp47":"mk","name":"Macedonian","label":"Ма"},
  {"lang":"tgl","bcp47":"fil","name":"Tagalog","label":"Tl"},
  {"lang":"tok","bcp47":"tok","name":"Toki Pona","label":"Tp"},
  {"lang":"ara","bcp47":"ar","name":"Arabic","label":"ع"},
  {"lang":"dan","bcp47":"da","name":"Danish","label":"Da"},
  {"lang":"tat","bcp47":"tt","name":"Tatar","label":"Тт"},
  {"lang":"swe","bcp47":"sv","name":"Swedish","label":"Sv"},
  {"lang":"lat","bcp47":"la","name":"Latin","label":"La"},
  {"lang":"srp","bcp47":"sr","name":"Serbian","label":"Ср"},
  {"lang":"tig","bcp47":"tig","name":"Tigre","label":"ትግ"},
  {"lang":"hye","bcp47":"hy","name":"Eastern Armenian","label":"Ար"},
  {"lang":"ell","bcp47":"el","name":"Greek","label":"Ελ"},
  {"lang":"ina","bcp47":"ia","name":"Interlingua","label":"Ia"},
  {"lang":"ron","bcp47":"ro","name":"Romanian","label":"Ro"},
  {"lang":"lfn","bcp47":"lfn","name":"Lingua Franca Nova","label":"Lf"},
  {"lang":"tlh","bcp47":"tlh","name":"Klingon","label":"tlh"},
  {"lang":"pes","bcp47":"fa","name":"Persian","label":"فا"},
  {"lang":"vie","bcp47":"vi","name":"Vietnamese","label":"Vi"},
  {"lang":"slk","bcp47":"sk","name":"Slovak","label":"Sk"},
  {"lang":"ind","bcp47":"id","name":"Indonesian","label":"Id"},
  {"lang":"yid","bcp47":"yi","name":"Yiddish","label":"יי"},
  {"lang":"bul","bcp47":"bg","name":"Bulgarian","label":"Бг"},
  {"lang":"swc","bcp47":"sw-CD","name":"Congo Swahili","label":"Sw"},
  {"lang":"oci","bcp47":"oc","name":"Occitan","label":"Oc"},
  {"lang":"shi","bcp47":"shi","name":"Tashelhit","label":"Ta"},
  {"lang":"hau","bcp47":"ha","name":"Hausa","label":"Ha"},
  {"lang":"zgh","bcp47":"zgh","name":"Standard Moroccan Tamazight","label":"Tm"},
  {"lang":"yue","bcp47":"yue","name":"Cantonese","label":"粵"},
  {"lang":"nds","bcp47":"nds","name":"Low German (Low Saxon)","label":"Nd"},
  {"lang":"nob","bcp47":"nb","name":"Norwegian Bokmål","label":"Nb"},
  {"lang":"jbo","bcp47":"jbo","name":"Lojban","label":"jb"},
  {"lang":"ben","bcp47":"bn","name":"Bengali","label":"ব"},
  {"lang":"hin","bcp47":"hi","name":"Hindi","label":"हि"},
  {"lang":"kor","bcp47":"ko","name":"Korean","label":"한"},
  {"lang":"asm","bcp47":"as","name":"Assamese","label":"অ"},
  {"lang":"bel","bcp47":"be","name":"Belarusian","label":"Бе"},
  {"lang":"nnb","bcp47":"nnb","name":"Nande","label":"Na"},
  {"lang":"ido","bcp47":"io","name":"Ido","label":"Io"},
  {"lang":"lvs","bcp47":"lv","name":"Latvian","label":"Lv"},
  {"lang":"isl","bcp47":"is","name":"Icelandic","label":"Ís"},
  {"lang":"ckb","bcp47":"ckb","name":"Central Kurdish (Soranî)","label":"ک"},
  {"lang":"nno","bcp47":"nn","name":"Norwegian Nynorsk","label":"Nn"},
  {"lang":"ile","bcp47":"ie","name":"Interlingue","label":"Ie"},
  {"lang":"aze","bcp47":"az","name":"Azerbaijani","label":"Az"},
  {"lang":"gos","bcp47":"gos","name":"Gronings","label":"Gr"},
  {"lang":"kmr","bcp47":"ku","name":"Northern Kurdish (Kurmancî)","label":"Ku"},
  {"lang":"cat","bcp47":"ca","name":"Catalan","label":"Ca"},
  {"lang":"bre","bcp47":"br","name":"Breton","label":"Br"},
  {"lang":"uig","bcp47":"ug","name":"Uyghur","label":"ئۇ"},
  {"lang":"zsm","bcp47":"ms","name":"Malay","label":"Ms"},
  {"lang":"glg","bcp47":"gl","name":"Galician","label":"Gl"},
  {"lang":"oss","bcp47":"os","name":"Ossetian","label":"Ос"},
  {"lang":"kat","bcp47":"ka","name":"Georgian","label":"ქა"},
  {"lang":"tuk","bcp47":"tk","name":"Turkmen","label":"Tm"},
  {"lang":"tha","bcp47":"th","name":"Thai","label":"ไท"},
  {"lang":"vol","bcp47":"vo","name":"Volapük","label":"Vo"},
  {"lang":"eus","bcp47":"eu","name":"Basque","label":"Eu"},
  {"lang":"sat","bcp47":"sat","name":"Santali","label":"ᱥ"},
  {"lang":"est","bcp47":"et","name":"Estonian","label":"Et"},
  {"lang":"hrv","bcp47":"hr","name":"Croatian","label":"Hr"},
  {"lang":"prg","bcp47":"prg","name":"Old Prussian","label":"Pr"},
  {"lang":"kzj","bcp47":"dtp","name":"Coastal Kadazan","label":"Ka"},
  {"lang":"run","bcp47":"rn","name":"Kirundi","label":"Ru"},
  {"lang":"udm","bcp47":"udm","name":"Udmurt","label":"Уд"},
  {"lang":"lin","bcp47":"ln","name":"Lingala","label":"Li"},
  {"lang":"wuu","bcp47":"wuu","name":"Shanghainese","label":"沪"},
  {"lang":"afr","bcp47":"af","name":"Afrikaans","label":"Af"},
  {"lang":"swh","bcp47":"sw","name":"Swahili","label":"Sw"},
  {"lang":"npi","bcp47":"ne","name":"Nepali","label":"ने"},
  {"lang":"kaz","bcp47":"kk","name":"Kazakh","label":"Қз"},
  {"lang":"mhr","bcp47":"chm","name":"Meadow Mari","label":"Мар"},
  {"lang":"avk","bcp47":"avk","name":"Kotava","label":"Kv"},
  {"lang":"tir","bcp47":"ti","name":"Tigrinya","label":"ትግ"},
  {"lang":"cor","bcp47":"kw","name":"Cornish","label":"Kw"},
  {"lang":"rhg","bcp47":"rhg","name":"Rohingya","label":"Ru"},
  {"lang":"knc","bcp47":"kr","name":"Central Kanuri","label":"Kn"},
  {"lang":"slv","bcp47":"sl","name":"Slovenian","label":"Sl"},
  {"lang":"grn","bcp47":"gn","name":"Guarani","label":"Gu"},
  {"lang":"cbk","bcp47":"cbk","name":"Chavacano","label":"Cv"},
  {"lang":"frr","bcp47":"frr","name":"North Frisian","label":"Fr"},
  {"lang":"dtp","bcp47":"dtp","name":"Central Dusun","label":"Du"},
  {"lang":"gle","bcp47":"ga","name":"Irish","label":"Ga"},
  {"lang":"urd","bcp47":"ur","name":"Urdu","label":"ارد"},
  {"lang":"mon","bcp47":"mn","name":"Mongolian","label":"мон"},
  {"lang":"nus","bcp47":"nus","name":"Nuer","label":"Nu"},
  {"lang":"sqi","bcp47":"sq","name":"Albanian","label":"Sh"},
  {"lang":"ota","bcp47":"ota","name":"Ottoman Turkish","label":"عث"},
  {"lang":"ilo","bcp47":"ilo","name":"Ilocano","label":"Il"},
  {"lang":"khm","bcp47":"km","name":"Khmer","label":"ខ"},
  {"lang":"hrx","bcp47":"hrx","name":"Hunsrik","label":"Hu"},
  {"lang":"arq","bcp47":"arq","name":"Algerian Arabic","label":"جز"},
  {"lang":"hoc","bcp47":"hoc","name":"Ho","label":"Ho"},
  {"lang":"war","bcp47":"war","name":"Waray","label":"Wa"},
  {"lang":"kha","bcp47":"kha","name":"Khasi","label":"Ka"},
  {"lang":"zlm","bcp47":"zlm","name":"Malay (Vernacular)","label":"My"},
  {"lang":"rif","bcp47":"rif","name":"Tarifit","label":"Tr"},
  {"lang":"gcf","bcp47":"gcf","name":"Guadeloupean Creole French","label":"Gc"},
  {"lang":"lad","bcp47":"lad","name":"Ladino","label":"La"},
  {"lang":"swg","bcp47":"swg","name":"Swabian","label":"Sw"},
  {"lang":"lij","bcp47":"lij","name":"Ligurian","label":"Li"},
  {"lang":"xmf","bcp47":"xmf","name":"Mingrelian","label":"მი"},
  {"lang":"lzh","bcp47":"lzh","name":"Literary Chinese","label":"文"},
  {"lang":"cym","bcp47":"cy","name":"Welsh","label":"Cy"},
  {"lang":"zza","bcp47":"zza","name":"Zaza","label":"Za"},
  {"lang":"bos","bcp47":"bs","name":"Bosnian","label":"Bs"},
  {"lang":"chv","bcp47":"cv","name":"Chuvash","label":"Чў"},
  {"lang":"grc","bcp47":"grc","name":"Ancient Greek","label":"Ἑ"},
  {"lang":"ceb","bcp47":"ceb","name":"Cebuano","label":"Ce"},
  {"lang":"dsb","bcp47":"dsb","name":"Lower Sorbian","label":"Ds"},
  {"lang":"alt","bcp47":"alt","name":"Southern Altai","label":"Ал"},
  {"lang":"hsb","bcp47":"hsb","name":"Upper Sorbian","label":"Hs"},
  {"lang":"pam","bcp47":"pam","name":"Kapampangan","label":"Ka"},
  {"lang":"arz","bcp47":"arz","name":"Egyptian Arabic","label":"مص"},
  {"lang":"jav","bcp47":"jv","name":"Javanese","label":"Jv"},
  {"lang":"unknown","bcp47":"unknown","name":"unknown","label":"?"},
  {"lang":"pcd","bcp47":"pcd","name":"Picard","label":"Pi"},
  {"lang":"orv","bcp47":"orv","name":"Old East Slavic","label":"Ру"},
  {"lang":"uzb","bcp47":"uz","name":"Uzbek","label":"Uz"},
  {"lang":"gla","bcp47":"gd","name":"Scottish Gaelic","label":"Gd"},
  {"lang":"bua","bcp47":"bua","name":"Buryat","label":"Бу"},
  {"lang":"sdh","bcp47":"sdh","name":"Southern Kurdish","label":"کو"},
  {"lang":"rom","bcp47":"rom","name":"Romani","label":"Ro"},
  {"lang":"ltz","bcp47":"lb","name":"Luxembourgish","label":"Lb"},
  {"lang":"sah","bcp47":"sah","name":"Yakut","label":"Сх"},
  {"lang":"isv","bcp47":"isv","name":"Interslavic","label":"Sl"},
  {"lang":"csb","bcp47":"csb","name":"Kashubian","label":"Ks"},
  {"lang":"guc","bcp47":"guc","name":"Wayuu","label":"Wy"},
  {"lang":"ava","bcp47":"av","name":"Avar","label":"Ав"},
  {"lang":"mal","bcp47":"ml","name":"Malayalam","label":"മ"},
  {"lang":"szl","bcp47":"szl","name":"Silesian","label":"Śl"},
  {"lang":"xal","bcp47":"xal","name":"Kalmyk","label":"Хл"},
  {"lang":"pms","bcp47":"pms","name":"Piedmontese","label":"Pm"},
  {"lang":"ast","bcp47":"ast","name":"Asturian","label":"As"},
  {"lang":"nov","bcp47":"nov","name":"Novial","label":"No"},
  {"lang":"nst","bcp47":"nst","name":"Naga (Tangshang)","label":"Na"},
  {"lang":"bzt","bcp47":"bzt","name":"Brithenig","label":"Br"},
  {"lang":"sun","bcp47":"su","name":"Sundanese","label":"Su"},
  {"lang":"fry","bcp47":"fy","name":"Frisian","label":"Fy"},
  {"lang":"shy","bcp47":"shy","name":"Tachawit","label":"Ta"},
  {"lang":"mlt","bcp47":"mt","name":"Maltese","label":"Mt"},
  {"lang":"mus","bcp47":"mus","name":"Muskogee (Creek)","label":"Mu"},
  {"lang":"fkv","bcp47":"fkv","name":"Kven Finnish","label":"Kv"},
  {"lang":"thv","bcp47":"thv","name":"Tahaggart Tamahaq","label":"Tg"},
  {"lang":"mya","bcp47":"my","name":"Burmese","label":"မြ"},
  {"lang":"izh","bcp47":"izh","name":"Ingrian","label":"In"},
  {"lang":"kir","bcp47":"ky","name":"Kyrgyz","label":"Кы"},
  {"lang":"arn","bcp47":"arn","name":"Mapuche","label":"Ma"},
  {"lang":"tpn","bcp47":"tpn","name":"Tupinambá","label":"Tu"},
  {"lang":"tam","bcp47":"ta","name":"Tamil","label":"த"},
  {"lang":"crh","bcp47":"crh","name":"Crimean Tatar","label":"Қр"},
  {"lang":"ckt","bcp47":"ckt","name":"Chukchi","label":"Чк"},
  {"lang":"gsw","bcp47":"gsw","name":"Swiss German","label":"Sz"},
  {"lang":"nan","bcp47":"nan","name":"Min Nan Chinese","label":"閩"},
  {"lang":"mri","bcp47":"mi","name":"Maori","label":"Ma"},
  {"lang":"ain","bcp47":"ain","name":"Ainu","label":"アイ"},
  {"lang":"que","bcp47":"qu","name":"Quechua","label":"Qu"},
  {"lang":"fao","bcp47":"fo","name":"Faroese","label":"Fo"},
  {"lang":"max","bcp47":"max","name":"North Moluccan Malay","label":"Mm"},
  {"lang":"ang","bcp47":"ang","name":"Old English","label":"Æ"},
  {"lang":"vep","bcp47":"vep","name":"Veps","label":"Ve"},
  {"lang":"ori","bcp47":"or","name":"Odia (Oriya)","label":"ଓ"},
  {"lang":"lug","bcp47":"lg","name":"Luganda","label":"Lu"},
  {"lang":"myv","bcp47":"myv","name":"Erzya","label":"Эр"},
  {"lang":"bak","bcp47":"ba","name":"Bashkir","label":"Бш"},
  {"lang":"cha","bcp47":"ch","name":"Chamorro","label":"Ch"},
  {"lang":"tzl","bcp47":"tzl","name":"Talossan","label":"Tz"},
  {"lang":"ltg","bcp47":"ltg","name":"Latgalian","label":"Lg"},
  {"lang":"amh","bcp47":"am","name":"Amharic","label":"አማ"},
  {"lang":"kan","bcp47":"kn","name":"Kannada","label":"ಕ"},
  {"lang":"nog","bcp47":"nog","name":"Nogai","label":"Но"},
  {"lang":"mfa","bcp47":"mfa","name":"Kelantan-Pattani Malay","label":"Km"},
  {"lang":"tel","bcp47":"te","name":"Telugu","label":"తెల"},
  {"lang":"krc","bcp47":"krc","name":"Karachay-Balkar","label":"Кр"},
  {"lang":"tum","bcp47":"tum","name":"Tumbuka","label":"Tu"},
  {"lang":"vec","bcp47":"vec","name":"Venetian","label":"Ve"},
  {"lang":"kas","bcp47":"ks","name":"Kashmiri","label":"كش"},
  {"lang":"lez","bcp47":"lez","name":"Lezgi","label":"Лз"},
  {"lang":"got","bcp47":"got","name":"Gothic","label":"𐌲"},
  {"lang":"xho","bcp47":"xh","name":"Xhosa","label":"Xh"},
  {"lang":"awa","bcp47":"awa","name":"Awadhi","label":"अव"},
  {"lang":"bar","bcp47":"bar","name":"Bavarian","label":"Ba"},
  {"lang":"otk","bcp47":"otk","name":"Old Turkish","label":"𐰴"},
  {"lang":"nah","bcp47":"nah","name":"Nahuatl","label":"Na"},
  {"lang":"lao","bcp47":"lo","name":"Lao","label":"ລ"},
  {"lang":"sme","bcp47":"se","name":"Northern Sami","label":"Sa"},
  {"lang":"lzz","bcp47":"lzz","name":"Laz","label":"Lz"},
  {"lang":"tmr","bcp47":"tmr","name":"Jewish Babylonian Aramaic","label":"אר"},
  {"lang":"pan","bcp47":"pa","name":"Punjabi (Eastern)","label":"ਪੰ"},
  {"lang":"fro","bcp47":"fro","name":"Old French","label":"Of"},
  {"lang":"mwl","bcp47":"mwl","name":"Mirandese","label":"Mi"},
  {"lang":"som","bcp47":"so","name":"Somali","label":"So"},
  {"lang":"srn","bcp47":"srn","name":"Sranan Tongo","label":"Sr"},
  {"lang":"ldn","bcp47":"ldn","name":"Láadan","label":"Lá"},
  {"lang":"krl","bcp47":"krl","name":"Karelian","label":"Ka"},
  {"lang":"haw","bcp47":"haw","name":"Hawaiian","label":"Ha"},
  {"lang":"bal","bcp47":"bal","name":"Baluchi","label":"Bl"},
  {"lang":"sux","bcp47":"sux","name":"Sumerian","label":"𒅴"},
  {"lang":"kal","bcp47":"kl","name":"Greenlandic","label":"Kl"},
  {"lang":"guj","bcp47":"gu","name":"Gujarati","label":"ગુ"},
  {"lang":"qya","bcp47":"qya","name":"Quenya","label":"Qy"},
  {"lang":"stq","bcp47":"stq","name":"Saterland Frisian","label":"Sf"},
  {"lang":"san","bcp47":"sa","name":"Sanskrit","label":"सं"},
  {"lang":"liv","bcp47":"liv","name":"Livonian","label":"Li"},
  {"lang":"hbo","bcp47":"hbo","name":"Ancient Hebrew","label":"עת"},
  {"lang":"kum","bcp47":"kum","name":"Kumyk","label":"Ку"},
  {"lang":"bjn","bcp47":"bjn","name":"Banjar","label":"Bj"},
  {"lang":"enm","bcp47":"enm","name":"Middle English","label":"Me"},
  {"lang":"egl","bcp47":"egl","name":"Emilian","label":"Em"},
  {"lang":"mik","bcp47":"mik","name":"Hitchiti","label":"Hi"},
  {"lang":"skr","bcp47":"skr","name":"Saraiki","label":"سر"},
  {"lang":"kbd","bcp47":"kbd","name":"Kabardian","label":"Кб"},
  {"lang":"sjn","bcp47":"sjn","name":"Sindarin","label":"Sd"},
  {"lang":"afb","bcp47":"afb","name":"Gulf Arabic","label":"خل"},
  {"lang":"cho","bcp47":"cho","name":"Choctaw","label":"Ch"},
  {"lang":"ajp","bcp47":"ajp","name":"South Levantine Arabic","label":"شم"},
  {"lang":"min","bcp47":"min","name":"Minangkabau","label":"Mi"},
  {"lang":"rue","bcp47":"rue","name":"Rusyn","label":"Ру"},
  {"lang":"evn","bcp47":"evn","name":"Evenki","label":"Эв"},
  {"lang":"yor","bcp47":"yo","name":"Yoruba","label":"Yo"},
  {"lang":"non","bcp47":"non","name":"Old Norse","label":"ᚾ"},
  {"lang":"oji","bcp47":"oj","name":"Ojibwe","label":"Oj"},
  {"lang":"zul","bcp47":"zu","name":"Zulu","label":"Zu"},
  {"lang":"hat","bcp47":"ht","name":"Haitian Creole","label":"Ht"},
  {"lang":"dws","bcp47":"dws","name":"Dutton World Speedwords","label":"Dw"},
  {"lang":"wol","bcp47":"wo","name":"Wolof","label":"Wo"},
  {"lang":"arg","bcp47":"an","name":"Aragonese","label":"Ar"},
  {"lang":"tet","bcp47":"tet","name":"Tetun","label":"Te"},
  {"lang":"njo","bcp47":"njo","name":"Ao Naga","label":"Ao"},
  {"lang":"tpi","bcp47":"tpi","name":"Tok Pisin","label":"Tp"},
  {"lang":"apc","bcp47":"apc","name":"North Levantine Arabic","label":"شم"},
  {"lang":"ary","bcp47":"ary","name":"Moroccan Arabic","label":"مغ"},
  {"lang":"iba","bcp47":"iba","name":"Iban","label":"Ib"},
  {"lang":"bvy","bcp47":"bvy","name":"Baybayanon","label":"Ba"},
  {"lang":"shs","bcp47":"shs","name":"Shuswap","label":"Sh"},
  {"lang":"sco","bcp47":"sco","name":"Scots","label":"Sc"},
  {"lang":"mww","bcp47":"mww","name":"Hmong Daw (White)","label":"Hm"},
  {"lang":"tyv","bcp47":"tyv","name":"Tuvinian","label":"Ты"},
  {"lang":"pap","bcp47":"pap","name":"Papiamento","label":"Pa"},
  {"lang":"mrj","bcp47":"mrj","name":"Hill Mari","label":"Мар"},
  {"lang":"kjh","bcp47":"kjh","name":"Khakas","label":"Хк"},
  {"lang":"hyw","bcp47":"hyw","name":"Western Armenian","label":"Ար"},
  {"lang":"nav","bcp47":"nv","name":"Navajo","label":"Na"},
  {"lang":"lld","bcp47":"lld","name":"Ladin","label":"Ld"},
  {"lang":"cmo","bcp47":"cmo","name":"Central Mnong","label":"Mn"},
  {"lang":"ext","bcp47":"ext","name":"Extremaduran","label":"Ex"},
  {"lang":"smo","bcp47":"sm","name":"Samoan","label":"Sm"},
  {"lang":"ksh","bcp47":"ksh","name":"Kölsch","label":"Kö"},
  {"lang":"tgk","bcp47":"tg","name":"Tajik","label":"То"},
  {"lang":"afh","bcp47":"afh","name":"Afrihili","label":"Af"},
  {"lang":"moh","bcp47":"moh","name":"Mohawk","label":"Mo"},
  {"lang":"mlg","bcp47":"mg","name":"Malagasy","label":"Mg"},
  {"lang":"kpv","bcp47":"kv","name":"Komi-Zyrian","label":"Ком"},
  {"lang":"sin","bcp47":"si","name":"Sinhala","label":"සි"},
  {"lang":"pnb","bcp47":"lah","name":"Punjabi (Western)","label":"پن"},
  {"lang":"gag","bcp47":"gag","name":"Gagauz","label":"Ga"},
  {"lang":"kaa","bcp47":"kaa","name":"Karakalpak","label":"Қа"},
  {"lang":"tly","bcp47":"tly","name":"Talysh","label":"تل"},
  {"lang":"crs","bcp47":"crs","name":"Seychellois Creole","label":"Sc"},
  {"lang":"cycl","bcp47":"cycl","name":"CycL","label":"Cy"},
  {"lang":"nap","bcp47":"nap","name":"Neapolitan","label":"Np"},
  {"lang":"hak","bcp47":"hak","name":"Hakka Chinese","label":"客"},
  {"lang":"bam","bcp47":"bm","name":"Bambara","label":"Bm"},
  {"lang":"iii","bcp47":"ii","name":"Nuosu","label":"ꆈ"},
  {"lang":"pag","bcp47":"pag","name":"Pangasinan","label":"Pa"},
  {"lang":"pus","bcp47":"ps","name":"Pashto","label":"پش"},
  {"lang":"ppl","bcp47":"ppl","name":"Pipil","label":"Pi"},
  {"lang":"mgm","bcp47":"mgm","name":"Mambae","label":"Ma"},
  {"lang":"sma","bcp47":"sma","name":"Southern Sami","label":"Sa"},
  {"lang":"lut","bcp47":"lut","name":"Lushootseed","label":"Lu"},
  {"lang":"bod","bcp47":"bo","name":"Tibetan","label":"བ"},
  {"lang":"pdc","bcp47":"pdc","name":"Pennsylvania German","label":"Pg"},
  {"lang":"bfz","bcp47":"bfz","name":"Mahasu Pahari","label":"Ma"},
  {"lang":"bho","bcp47":"bho","name":"Bhojpuri","label":"भो"},
  {"lang":"tts","bcp47":"tts","name":"Isan","label":"อี"},
  {"lang":"pal","bcp47":"pal","name":"Middle Persian (Pahlavi)","label":"𐭯"},
  {"lang":"chn","bcp47":"chn","name":"Chinook Jargon","label":"Ch"},
  {"lang":"wln","bcp47":"wa","name":"Walloon","label":"Wa"},
  {"lang":"crk","bcp47":"crk","name":"Plains Cree","label":"Cr"},
  {"lang":"bom","bcp47":"bom","name":"Berom","label":"Be"},
  {"lang":"acm","bcp47":"acm","name":"Iraqi Arabic","label":"عر"},
  {"lang":"ike","bcp47":"iu","name":"Inuktitut","label":"ᐃᓄ"},
  {"lang":"sna","bcp47":"sn","name":"Shona","label":"Sn"},
  {"lang":"sgs","bcp47":"sgs","name":"Samogitian","label":"Sm"},
  {"lang":"lim","bcp47":"li","name":"Limburgish","label":"Li"},
  {"lang":"che","bcp47":"ce","name":"Chechen","label":"Чч"},
  {"lang":"ibo","bcp47":"ig","name":"Igbo","label":"Ig"},
  {"lang":"nya","bcp47":"ny","name":"Chinyanja","label":"Ny"},
  {"lang":"koi","bcp47":"koi","name":"Komi-Permyak","label":"Ком"},
  {"lang":"drt","bcp47":"drt","name":"Drents","label":"Dr"},
  {"lang":"hil","bcp47":"hil","name":"Hiligaynon","label":"Hi"},
  {"lang":"fij","bcp47":"fj","name":"Fijian","label":"Fj"},
  {"lang":"ngu","bcp47":"ngu","name":"Guerrero Nahuatl","label":"Na"},
  {"lang":"ryu","bcp47":"ryu","name":"Okinawan","label":"沖"},
  {"lang":"tsn","bcp47":"tn","name":"Setswana","label":"Tw"},
  {"lang":"dar","bcp47":"dar","name":"Dargwa","label":"Дар"},
  {"lang":"div","bcp47":"dv","name":"Dhivehi","label":"ދ"},
  {"lang":"glv","bcp47":"gv","name":"Manx","label":"Mx"},
  {"lang":"nch","bcp47":"nch","name":"Central Huasteca Nahuatl","label":"Na"},
  {"lang":"abk","bcp47":"ab","name":"Abkhaz","label":"Аб"},
  {"lang":"gbm","bcp47":"gbm","name":"Garhwali","label":"गढ़"},
  {"lang":"niu","bcp47":"niu","name":"Niuean","label":"Ni"},
  {"lang":"fuv","bcp47":"fuv","name":"Nigerian Fulfulde","label":"Fu"},
  {"lang":"scn","bcp47":"scn","name":"Sicilian","label":"Si"},
  {"lang":"pau","bcp47":"pau","name":"Palauan","label":"Pa"},
  {"lang":"jam","bcp47":"jam","name":"Jamaican Patois","label":"Ja"},
  {"lang":"igs","bcp47":"igs","name":"Interglossa","label":"Ig"},
  {"lang":"fur","bcp47":"fur","name":"Friulian","label":"Fr"},
  {"lang":"hif","bcp47":"hif","name":"Fiji Hindi","label":"Fi"},
  {"lang":"frm","bcp47":"frm","name":"Middle French","label":"Mf"},
  {"lang":"yua","bcp47":"yua","name":"Yucatec Maya","label":"Ya"},
  {"lang":"osp","bcp47":"osp","name":"Old Spanish","label":"Os"},
  {"lang":"rap","bcp47":"rap","name":"Rapa Nui","label":"Ra"},
  {"lang":"ady","bcp47":"ady","name":"Adyghe","label":"Ады"},
  {"lang":"cay","bcp47":"cay","name":"Cayuga","label":"Ca"},
  {"lang":"kin","bcp47":"rw","name":"Kinyarwanda","label":"Rw"},
  {"lang":"dng","bcp47":"dng","name":"Dungan","label":"Ду"},
  {"lang":"umb","bcp47":"umb","name":"Umbundu","label":"Um"},
  {"lang":"gaa","bcp47":"gaa","name":"Ga","label":"Ga"},
  {"lang":"tah","bcp47":"ty","name":"Tahitian","label":"Ta"},
  {"lang":"chr","bcp47":"chr","name":"Cherokee","label":"Ꮳ"},
  {"lang":"lmo","bcp47":"lmo","name":"Lombard","label":"Lm"},
  {"lang":"bis","bcp47":"bi","name":"Bislama","label":"Bi"},
  {"lang":"ood","bcp47":"ood","name":"O'odham","label":"Oo"},
  {"lang":"aln","bcp47":"aln","name":"Gheg Albanian","label":"Sh"},
  {"lang":"cos","bcp47":"co","name":"Corsican","label":"Co"},
  {"lang":"mvv","bcp47":"mvv","name":"Tagal Murut","label":"Tm"},
  {"lang":"akl","bcp47":"akl","name":"Aklanon","label":"Ak"},
  {"lang":"mah","bcp47":"mh","name":"Marshallese","label":"Ma"},
  {"lang":"roh","bcp47":"rm","name":"Romansh","label":"Rm"},
  {"lang":"ewe","bcp47":"ee","name":"Ewe","label":"Ew"},
  {"lang":"lkt","bcp47":"lkt","name":"Lakota","label":"La"},
  {"lang":"kek","bcp47":"kek","name":"Kekchi (Q'eqchi')","label":"Qe"},
  {"lang":"aoz","bcp47":"aoz","name":"Uab Meto","label":"Ua"},
  {"lang":"qxq","bcp47":"qxq","name":"Qashqai","label":"Qa"},
  {"lang":"ton","bcp47":"to","name":"Tongan","label":"To"},
  {"lang":"klj","bcp47":"klj","name":"Khalaj","label":"Kh"},
  {"lang":"lou","bcp47":"lou","name":"Louisiana Creole","label":"Lc"},
  {"lang":"oar","bcp47":"oar","name":"Old Aramaic","label":"אר"},
  {"lang":"pli","bcp47":"pi","name":"Pali","label":"पा"},
  {"lang":"inh","bcp47":"inh","name":"Ingush","label":"Инг"},
  {"lang":"toi","bcp47":"toi","name":"Tonga (Zambezi)","label":"Tg"},
  {"lang":"ngt","bcp47":"ngt","name":"Ngeq","label":"Ng"},
  {"lang":"mic","bcp47":"mic","name":"Mi'kmaq","label":"Mi"},
  {"lang":"cjy","bcp47":"cjy","name":"Jin Chinese","label":"晋"},
  {"lang":"sva","bcp47":"sva","name":"Svan","label":"Sv"},
  {"lang":"jpa","bcp47":"jpa","name":"Jewish Palestinian Aramaic","label":"אר"},
  {"lang":"new","bcp47":"new","name":"Newari","label":"ने"},
  {"lang":"srd","bcp47":"sc","name":"Sardinian","label":"Sa"},
  {"lang":"syl","bcp47":"syl","name":"Sylheti","label":"সि"},
  {"lang":"tvl","bcp47":"tvl","name":"Tuvaluan","label":"Tu"},
  {"lang":"mdr","bcp47":"mdr","name":"Mandar","label":"Ma"},
  {"lang":"vro","bcp47":"vro","name":"Võro","label":"Võ"},
  {"lang":"bcl","bcp47":"bik","name":"Central Bikol","label":"Bi"},
  {"lang":"phn","bcp47":"phn","name":"Phoenician","label":"𐤐"},
  {"lang":"urh","bcp47":"urh","name":"Urhobo","label":"Ur"},
  {"lang":"nlv","bcp47":"nlv","name":"Orizaba Nahuatl","label":"Na"},
  {"lang":"gil","bcp47":"gil","name":"Gilbertese","label":"Gi"},
  {"lang":"lbe","bcp47":"lbe","name":"Lak","label":"Лк"},
  {"lang":"ofs","bcp47":"ofs","name":"Old Frisian","label":"Of"},
  {"lang":"aym","bcp47":"ay","name":"Aymara","label":"Ay"},
  {"lang":"xqa","bcp47":"xqa","name":"Karakhanid","label":"ك"},
  {"lang":"mnr","bcp47":"mnr","name":"Mono (USA)","label":"Mo"},
  {"lang":"abq","bcp47":"abq","name":"Abaza","label":"Аб"},
  {"lang":"emx","bcp47":"emx","name":"Erromintxela","label":"Er"},
  {"lang":"zea","bcp47":"zea","name":"Zeelandic","label":"Ze"},
  {"lang":"sag","bcp47":"sg","name":"Sango","label":"Sa"},
  {"lang":"fuc","bcp47":"ff","name":"Pulaar","label":"Pu"},
  {"lang":"tkl","bcp47":"tkl","name":"Tokelauan","label":"Tk"},
  {"lang":"mni","bcp47":"mni","name":"Meitei","label":"মে"},
  {"lang":"nau","bcp47":"na","name":"Nauruan","label":"Na"},
  {"lang":"brx","bcp47":"brx","name":"Bodo","label":"Bo"},
  {"lang":"kam","bcp47":"kam","name":"Kamba","label":"Ka"},
  {"lang":"gom","bcp47":"gom","name":"Konkani (Goan)","label":"कों"},
  {"lang":"gaz","bcp47":"om","name":"West-Central Oromo","label":"Or"},
  {"lang":"laa","bcp47":"laa","name":"Southern Subanen","label":"Su"},
  {"lang":"mdf","bcp47":"mdf","name":"Moksha","label":"Мо"},
  {"lang":"jdt","bcp47":"jdt","name":"Juhuri (Judeo-Tat)","label":"Жу"},
  {"lang":"mnw","bcp47":"mnw","name":"Mon","label":"ဒ"},
  {"lang":"chg","bcp47":"chg","name":"Chagatai","label":"چا"},
  {"lang":"guw","bcp47":"guw","name":"Gun","label":"Gu"},
  {"lang":"mai","bcp47":"mai","name":"Maithili","label":"मै"},
  {"lang":"quc","bcp47":"quc","name":"K'iche'","label":"Ki"},
  {"lang":"mad","bcp47":"mad","name":"Madurese","label":"Ma"},
  {"lang":"cpi","bcp47":"cpi","name":"Chinese Pidgin English","label":"Pe"},
  {"lang":"ban","bcp47":"ban","name":"Balinese","label":"Ba"},
  {"lang":"ssw","bcp47":"ss","name":"Swazi","label":"Sw"},
  {"lang":"diq","bcp47":"zza","name":"Southern Zaza (Dimli)","label":"Zd"},
  {"lang":"kiu","bcp47":"kiu","name":"Northern Zaza (Kirmanjki)","label":"Zk"},
  {"lang":"aii","bcp47":"aii","name":"Assyrian Neo-Aramaic","label":"ܐܣ"},
  {"lang":"mfe","bcp47":"mfe","name":"Morisyen","label":"Mo"},
  {"lang":"snd","bcp47":"sd","name":"Sindhi","label":"سن"},
  {"lang":"tmw","bcp47":"tmw","name":"Temuan","label":"Te"},
  {"lang":"tso","bcp47":"ts","name":"Tsonga","label":"Ts"},
  {"lang":"hsn","bcp47":"hsn","name":"Xiang Chinese","label":"湘"},
  {"lang":"kxi","bcp47":"kxi","name":"Keningau Murut","label":"Km"},
  {"lang":"hnj","bcp47":"hnj","name":"Hmong Njua (Green)","label":"Hm"},
  {"lang":"syc","bcp47":"syc","name":"Syriac","label":"ܣܘ"},
  {"lang":"osx","bcp47":"osx","name":"Old Saxon","label":"Os"},
  {"lang":"hdn","bcp47":"hai","name":"Northern Haida","label":"Ha"},
  {"lang":"ayl","bcp47":"ayl","name":"Libyan Arabic","label":"لي"},
  {"lang":"gan","bcp47":"gan","name":"Gan Chinese","label":"贛"},
  {"lang":"pfl","bcp47":"pfl","name":"Palatine German","label":"Pf"},
  {"lang":"sot","bcp47":"st","name":"Southern Sotho","label":"So"},
  {"lang":"rel","bcp47":"rel","name":"Rendille","label":"Re"},
  {"lang":"nys","bcp47":"nys","name":"Nyungar","label":"Ny"},
  {"lang":"mnc","bcp47":"mnc","name":"Manchu","label":"满"},
  {"lang":"hax","bcp47":"hax","name":"Southern Haida","label":"Ha"},
  {"lang":"cyo","bcp47":"cyo","name":"Cuyonon","label":"Cu"}
];